### ISSUE TITLE
dip1000 issue

### ISSUE THREAD

**Issue by o3o** [burner/FuzzyCopy#2]
Hi Robert,

Has I written [here](https://forum.dlang.org/post/bhxpqxxsjxfhvqwropst@forum.dlang.org)
```json
"dflags": ["-dip1000", "-dip25"],
```
brokens my project. 

Rikki observs:

> DIP 1000 is an experimental addition to D, that is yet to be complete.
It is a compiler switch for a reason, it isn't ready for usage, only some experimentation.

What do you think? 
Is it  possible to remove it?

**Comment by o3o** [comment]
Thank you Robert!

**Comment by burner** [comment]
thank you for reporting
